general:
  data_base_dir: /app/data
  version: 1.0
  description: "Default configuration for MONAIAuto3dSeg (dicom in, dicom out)"

execute:
- DicomImporter
- NiftiConverter
- Auto3dSegRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: '%Modality'

  DsegConverter:
    model_name: Auto3dSeg
    body_part_examined: CHEST
    source_segs: nifti:mod=seg
    #json_config_path: /app/models/auto3dseg/config/Auto3DSeg-TS-V2-Abdominal.json
    json_config_path: /app/models/auto3dseg/config/auto-gen-auto3dseg.json
 
    skip_empty_slices: True
  
  DataOrganizer:
    targets:
    - dicomseg:mod=seg-->[i:sid]/auto3dseg.seg.dcm
